### ISSUE TITLE
Correct instructions for installing ultralytics via Git

### ISSUE THREAD

**Issue by robmarkcole** [roboflow/notebooks#102]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

Any ultralytics

### Bug

The instructions currently are wrong. Correct are:

# Git clone method (for development)
# git clone https://github.com/ultralytics/ultralytics.git
# cd ultralytics
# pip install -e .

### Environment

All

### Minimal Reproducible Example

NA

### Additional

NA

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @robmarkcole 👋🏻! I'm on it!

**Comment by SkalskiP** [comment]
@robmarkcole done! Thanks for bringing that to my attention 🙏🏻
