### ISSUE TITLE
Error when running ByteTrack Installation Cell in the Vehicle Counting Tutorial

### ISSUE THREAD

**Issue by AT9991** [roboflow/notebooks#112]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

Track and Count Vehicles with YOLOv8 + ByteTRACK + Supervision

### Bug

Error when running the ByteTrack installation cell. ![Screenshot 2023-05-04 at 13 40 11](https://user-images.githubusercontent.com/64208663/236299040-a7514f28-3245-47e4-8271-67de2df89121.png)

### Environment

- Google Colab

### Minimal Reproducible Example

%cd {HOME}
!git clone https://github.com/ifzhang/ByteTrack.git
%cd {HOME}/ByteTrack

# workaround related to https://github.com/roboflow/notebooks/issues/80
!sed -i 's/onnx==1.8.1/onnx==1.9.0/g' requirements.txt

!pip3 install -q -r requirements.txt
!python3 setup.py -q develop
!pip install -q cython_bbox
!pip install -q onemetric

from IPython import display
display.clear_output()

import sys
sys.path.append(f"{HOME}/ByteTrack")

import yolox
print("yolox.__version__:", yolox.__version__)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @AT9991 👋🏻! I spent some time yesterday and fixed the `how-to-track-and-count-vehicles-with-yolov8.ipynb` notebook again. I'm closing the issue, however, feel free to reopen it if you'll face any more issues.

**Comment by encouver** [comment]
the issue still persists:

![image](https://github.com/roboflow/notebooks/assets/1783184/4b4d2d73-f11c-4cd3-81f9-f36c5f659d81)

**Comment by AT9991** [comment]
Just !pip install -q thop
