### ISSUE TITLE
yolo-nas AttributeError on sv.Dataset

### ISSUE THREAD

**Issue by AmirAflak** [roboflow/notebooks#123]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

https://github.com/roboflow/notebooks/blob/main/notebooks/train-yolo-nas-on-custom-dataset.ipynb

### Bug

I got below error at "Inference with trained model" part: 

![image](https://github.com/roboflow/notebooks/assets/84932095/6d2602e0-bdcd-470b-a3e6-c3d63ad6d835)

### Environment

Google Colab

### Minimal Reproducible Example

```python
ds = sv.Dataset.from_yolo(
    images_directory_path=f"{dataset.location}/test/images",
    annotations_directory_path=f"{dataset.location}/test/labels",
    data_yaml_path=f"{dataset.location}/data.yaml",
    force_masks=False
)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, once again @AmirAflak 👋🏻! I just released a fix for the bug you mentioned. I think it is solved. But feel free to reopen it if you face any issues.
