### ISSUE TITLE
 Trouble with the custom  model load Yolov8

### ISSUE THREAD

**Issue by alcarvalhox** [roboflow/notebooks#126]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

#!pip install ultralytics==8.0.20
!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from collections.abc import Iterable
from ultralytics import YOLO

model = YOLO(f'{HOME}/runs/detect/train5/weights/best.pt')
results = model.predict(source = '/content/drive/MyDrive/Yolo_V8/test/images', conf = 0.25)

### Bug

I have a trouble with the custom  model line code  : " model = YOLO(f'{HOME}/runs/detect/train5/weights/best.pt')
results = model.predict(source = '/content/drive/MyDrive/Yolo_V8/test/images', conf = 0.25) ' the following error occurs " AttributeError: Can't get attribute 'IterableSimpleNamespace' on <module 'ultralytics.yolo.utils' from '/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/__init__.py'>" someone can help i´ve tried some solutions but dont work until now. Tks !!!

### Environment

- Google Colab
- Python-3.10.11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @alcarvalhox 👋🏻! Sorry for the late response. I was quite busy. It looks like this problem originates in the YOLOv8 code. I recommend opening a new issue in YOLOv8 [repository](https://github.com/ultralytics/ultralytics). Maybe they will be able to help you.

I'm closing the issue for now, but feel free to reopen it if you won't get any help there.
