### ISSUE TITLE
in train-huggingface-detr-on-custom-dataset.ipynb how to do detewction on image and video

### ISSUE THREAD

**Issue by VYRION-Ai** [roboflow/notebooks#139]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

i do traing using https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-huggingface-detr-on-custom-dataset.ipynb#scrollTo=A6YfGgeATvbR and i got two files pytorch_model.bin and  epoch=6-step=308.ckpt  , and close the colab sesion , i need to do detection now, what should i do and how ? please help @SkalskiP @ca

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VYRION-Ai** [comment]
@SkalskiP thank you very much it works with me now.

**Comment by SkalskiP** [comment]
@VYRION-Ai this is awesome to hear!
