### ISSUE TITLE
i need to draw the training curve for detr object detection

### ISSUE THREAD

**Issue by VYRION-Ai** [roboflow/notebooks#140]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description
@SkalskiP 
i run training on custom dataset dert object detection  https://github.com/roboflow/notebooks/blob/main/notebooks/train-huggingface-detr-on-custom-dataset.ipynb  and i save output and close colab session  , i need to get training curves , how to get that after session closed (i have the output)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VYRION-Ai** [comment]
%load_ext tensorboard
%tensorboard --logdir /content/lightning_logs/version_3 --port=6007

**Comment by SkalskiP** [comment]
Hi @VYRION-Ai 👋🏻! Sorry for the late reply. I was quite busy. I'm glad you managed to solve your problem.

**Comment by VYRION-Ai** [comment]
@SkalskiP thank you
