### ISSUE TITLE
 No module named 'ultralytics.yolo.utils.callbacks.dvc'

### ISSUE THREAD

**Issue by NatalieCheong** [roboflow/notebooks#146]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[Track and Count Vehicles with YOLOv8 + ByteTRACK + Supervision]. Hi, when I follow this tutorial: Track and Count Objects Using YOLOv8 and using the provided notebook. When I implement the last cell got an error:  No module named 'ultralytics.yolo.utils.callbacks.dvc'. Because of this error, I can't implement the same cell for the candies.mp4 from the same tutorial. 

### Bug

![Screenshot 2023-06-11 at 10 34 08 AM](https://github.com/roboflow/notebooks/assets/50092072/0c278df5-5fab-4083-9b4d-811e6c408183)
![Screenshot 2023-06-11 at 10 33 59 AM](https://github.com/roboflow/notebooks/assets/50092072/526f9e56-bf3c-4dc0-8b0c-f4e22a682bac)

### Environment

Google Colab

### Minimal Reproducible Example

```
When run the code snippet, it throws an error: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-26-5c4bce63dff3> in <cell line: 17>()
     19     for frame in tqdm(generator, total=video_info.total_frames):
     20         # model prediction on single frame and conversion to supervision Detections
---> 21         results = model(frame)[0]
     22         detections = Detections(
     23             xyxy=results[0].boxes.xyxy.cpu().numpy(),

4 frames
/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/callbacks/base.py in add_integration_callbacks(instance)

ModuleNotFoundError: No module named 'ultralytics.yolo.utils.callbacks.dvc'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by NatalieCheong** [comment]
Hi, thank you for the reply. Yes. It was happening in your current notebook. I was follow the tutorial 'Track and Count Objects Using YOLOv8' and I click the 'tutorial' button in this tutorial which direct me to Google Colab notebook, and the notebook is: how-to-track-and-count-vehicles-with-yolov8.ipynb.

**Comment by SkalskiP** [comment]
@NatalieCheong I'll investigate today 🙏🏻

**Comment by SkalskiP** [comment]
It looks like the problem solved itself. I'm closing the issue.
