### ISSUE TITLE
Error installing super-gradients==3.1.1

### ISSUE THREAD

**Issue by kenhuangsy** [roboflow/notebooks#171]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

I'm trying to follow the google colab notebook for training YOLO-NAS but I am coming across an error when attempting to pip install super-gradients==3.1.1.

### Bug

![image](https://github.com/roboflow/notebooks/assets/87556616/742ec638-9042-41b6-aca1-4ae7a9341eac)

I keep getting this error and I have tried it locally as well and it's not working either. Please help me. 

### Environment

- Google Colab: Python 3.10.12, torch = 2.0.1
- Locally: Ubuntu latest, Python 3.9.16, torch = 2.1.0

### Minimal Reproducible Example

I am just copying the code from the colab notebook.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AhnHyeon-Jin** [comment]
! pip install git+https://github.com/Deci-AI/super-gradients/releases/tag/3.1.1  --upgrade &> /dev/null
!pip install -q roboflow
!pip install -q supervision

**Comment by kenhuangsy** [comment]
Thank you!
