### ISSUE TITLE
"How to Train YOLO-NAS on Custom Dataset" does not build pycocotools

### ISSUE THREAD

**Issue by rafcab** [roboflow/notebooks#172]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

How to Train YOLO-NAS on Custom Dataset

### Bug

When running the second step in Google Colab, the one titled 'Install YOLO-NAS', gives an error :
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

### Environment

Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AhnHyeon-Jin** [comment]
I solved this same issue

! pip install git+https://github.com/Deci-AI/super-gradients/releases/tag/3.1.1  --upgrade &> /dev/null
!pip install -q roboflow
!pip install -q supervision

**Comment by SkalskiP** [comment]
Hi @AhnHyeon-Jin 👋🏻! Awesome! Would you like to create PR with the fix?

**Comment by arrafi-musabbir** [comment]
> I solved this same issue
> ! pip install git+https://github.com/Deci-AI/super-gradients/releases/tag/3.1.1 --upgrade &> /dev/null

This didn't help in my case on collab. I solved it by following [the instructions ](https://github.com/Deci-AI/super-gradients#quick-installation-1) on their GitHub repo and installed `super-gradients` like this:
```pip install git+https://github.com/Deci-AI/super-gradients.git@stable```

**Comment by medhanshrath-t** [comment]
> > I solved this same issue
> > ! pip install git+https://github.com/Deci-AI/super-gradients/releases/tag/3.1.1 --upgrade &> /dev/null
> 
> This didn't help in my case on collab. I solved it by following [the instructions ](https://github.com/Deci-AI/super-gradients#quick-installation-1) on their GitHub repo and installed `super-gradients` like this: `pip install git+https://github.com/Deci-AI/super-gradients.git@stable`

This worked for me too

**Comment by SkalskiP** [comment]
Thanks @arrafi-musabbir 🙏🏻 I just updated our YOLO-NAS notebook.

**Comment by Darrshan-Sankar** [comment]
I wanted to reopen this issue, as i get error for the following code:
```python
import cv2

image = cv2.imread(SOURCE_IMAGE_PATH)
result = list(model.predict(image, conf=0.35))[0]
```
I get the following error:
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-71f83f1aa3bd>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 image = cv2.imread(SOURCE_IMAGE_PATH)
----> 4 result = list(model.predict(image, conf=0.35))[0]

TypeError: 'ImageDetectionPrediction' object is not iterable
```
I ran the following notebook: ```https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolo-nas-on-custom-dataset.ipynb``` in colab
