### ISSUE TITLE
local operation  without sign in foboflow

### ISSUE THREAD

**Issue by foxnight2** [roboflow/notebooks#187]
Can the roboflow tool label images on my local computer without upload images ?
All the operation is on my computer without public?

I am the junior. Although I already use the roboflow and it have to sign in my account and upload my custom data.

**Comment by capjamesg** [comment]
Hello @foxnight2! Roboflow does not offer an annotation tool you can run on your own computer. You can use [Autodistill](https://github.com/autodistill/autodistill) to automatically label images according to a text prompt on your computer, however.
