### ISSUE TITLE
[Contribution] how-to-track-and-count-vehicles-with-yolov8.ipynb updated with latest Supervision 0.13.0 API

### ISSUE THREAD

**Issue by grhaonan** [roboflow/notebooks#189]
Hi team,

Thanks for your awesome work on the Supervison, it is fantastic!

I tried to follow your notebook at: 
https://github.com/roboflow/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb 
to get my head around how to do the tracking and counting with Supervision but found it is quite out of date.

Fortunately, your documentation is clear to follow so I refactored the notebook with the latest API (0.13.0) and there are quite a few changes compared with your original version. Main changes:

- Removing section "ByteTrack"
- Removing section "Tracking utils"
- Refactoring all necessary Classes or methods, such as LineCounter to LineZone, LineCounterAnnotator to LineZoneAnnotator plot_image etc
- Replace video loop by VideoSink to process_video

I am happy to share it so the whole community can benefit from my work but I understand you may would like to keep it as it is as the API is not stable yet.

In case you are interested and would like me to make this contribution, there are two options you may like to proceed?

Option 1: I submit a PR to replace the original notebook

Option 2: I submit a PR to add my version with a specific file name (let me know your preferred naming convention) so it is clear that this new notebook is for Supervision 0.13.0. 

Option 3: No action

Option 4: ?

The refactored version for your review: https://colab.research.google.com/drive/11Enps_V9D3Bd7UVAFuCtV2DGkyiPYJVp?usp=sharing

Again, thanks for your great work on Supervision, we are excited!

**Comment by grhaonan** [comment]
@SkalskiP cool, cool, thanks for your quick reply and I am fine with your plan.

I am not  100% sure if I understand your plan, but I have submitted a PR (https://github.com/roboflow/notebooks/pull/190) to upload this new notebook under notebooks folder.

Option 1: you would like to link the new notebook only instead of having a physical copy under notebooks -> then please reject my PR and  I will update the original notebook with a link to my colab address -> send a new PR

Option 2: you would like to have both a phycial copy and a new link -> I can then send another PR with a link added in the original notebook pointing to this phycial copy under notebooks folder once you merge https://github.com/roboflow/notebooks/pull/190

**Comment by SkalskiP** [comment]
Hi, @grhaonan 👋🏻 Good! Let's move the conversation to your PR. To have everything in one place.
