### ISSUE TITLE
403 - Forbidden for dfl-bundesliga-data-shootout dataset

### ISSUE THREAD

**Issue by totuta** [roboflow/notebooks#19]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

how-to-track-football-players.ipynb

### Bug

Hi, I was running

```
%cd {HOME}
!kaggle competitions files -c dfl-bundesliga-data-shootout | \
grep clips | head -20 | \
awk '{print $1}' | \
while read -r line; \
  do kaggle competitions download -c dfl-bundesliga-data-shootout -f $line -p clips --quiet; \
  unzip ${line}.zip -d clips && rm ${line}.zip; \
  done
```

and got this error

`403 - Forbidden unzip:  cannot find or open clips/0a2d9b_1.mp4.zip`

And when I visit the Kaggle competition site at https://www.kaggle.com/competitions/dfl-bundesliga-data-shootout/rules, it says:

`New entrants are currently not allowed. You will be able to accept the rules and submit late predictions after the competition completes.`

Is it because the dataset is currently locked?

### Environment

- Google Colab on GPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @totuta 👋🏻! Thank you for being interested in our tutorials. This problem is related to Kaggle not allowing new people to download the data for the next 9 days (most likely). I still have access to that data as I participated in the competition. I'll zip the clips directory and drop it on my google drive.

**Comment by totuta** [comment]
@SkalskiP 
Thank you very much for sharing the files!

I will close this issue when the data is available from Kaggle again.
For other people's reference.

**Comment by SkalskiP** [comment]
Great, @totuta!

**Comment by totuta** [comment]
Now I can confirm that the original Kaggle download page is back to normal

**Comment by SkalskiP** [comment]
This is great @totuta! Thank you very much for the confirmation :)
