### ISSUE TITLE
Tuple Unpack Problem in Byte Tracker of Supervision: 0.18.0

### ISSUE THREAD

**Issue by SyedAanif** [roboflow/notebooks#241]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

Updated notebook: notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb

### Bug

In the `Byte Tracker` of `Supervision version: 0.18.0`, there is a **tuple unpack problem** for `detections`.

PFA screenshot of the same version issue and the fix for the same.

This will help to run the notebook properly.

![SingleFrameProcess](https://github.com/roboflow/notebooks/assets/66770875/6ac889cf-e032-4112-9420-06a8dbbe5043)

![WholeVideoProcess](https://github.com/roboflow/notebooks/assets/66770875/87c5d17a-7215-44cf-b06a-58fde2fadced)

### Environment

- Google Colab

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @SyedAanif 👋🏻 ! Thanks for letting us know. Would you like to submit PR with fix?

**Comment by SkalskiP** [comment]
This one is solved already.
