### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

### ISSUE THREAD

**Issue by chinmayeebidaye** [roboflow/notebooks#272]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[Track and Count Vehicles with YOLOv8 + ByteTRACK + Supervision](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb)

### Bug

0: 384x640 1 person, 1 backpack, 3901.6ms
Speed: 6.2ms preprocess, 3901.6ms inference, 1.8ms postprocess per image at shape (1, 3, 384, 640)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-30-960ca66f206c>](https://localhost:8080/#) in <cell line: 22>()
     31     )
     32 
---> 33     tracks = byte_tracker.update(
     34         output_results=detections2boxes(detections=detections),
     35         img_info=frame.shape,

3 frames
[/content/ByteTrack/yolox/tracker/byte_tracker.py](https://localhost:8080/#) in update(self, output_results, img_info, img_size)
    187         if len(dets):
    188             '''Detections'''
--> 189             detections = [STrack(STrack.tlbr_to_tlwh(tlbr), s) for
    190                           (tlbr, s) in zip(dets, scores_keep)]
    191         else:

[/content/ByteTrack/yolox/tracker/byte_tracker.py](https://localhost:8080/#) in <listcomp>(.0)
    187         if len(dets):
    188             '''Detections'''
--> 189             detections = [STrack(STrack.tlbr_to_tlwh(tlbr), s) for
    190                           (tlbr, s) in zip(dets, scores_keep)]
    191         else:

[/content/ByteTrack/yolox/tracker/byte_tracker.py](https://localhost:8080/#) in __init__(self, tlwh, score)16 
     17         # wait activate
---> 18         self._tlwh = np.asarray(tlwh, dtype=float)
     19         self.kalman_filter = None
     20         self.mean, self.covariance = None, None

[/usr/local/lib/python3.10/dist-packages/numpy/__init__.py](https://localhost:8080/#) in __getattr__(attr)
    317 
    318         if attr in __former_attrs__:
--> 319             raise AttributeError(__former_attrs__[attr])
    320 
    321         if attr == 'testing':

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

### Environment

-Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by iurisilvio** [comment]
The error comes from https://github.com/ifzhang/ByteTrack/issues/386.

**Comment by chinmayeebidaye** [comment]
I followed the steps but i'm still getting the same error. Any idea why?

**Comment by iurisilvio** [comment]
This notebook is outdated:

> This notebook uses legacy versions of ByteTrack and Supervision. To be up to date, use our updated [notebook](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8-and-supervison.ipynb).

I'd suggest you to run with the [updated version](https://github.com/roboflow/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8-and-supervison.ipynb).

I tried to build ByteTrack, but many packages are outdated now.

**Comment by SkalskiP** [comment]
Hi, @chinmayeebidaye! 👋🏻 

Unfortunately, due to a conflict between the versions of NumPy in the Google Colab environment and the requirements set by ByteTrack, we cannot resolve this issue. However, as @iurisilvio recommended, I suggest using the [revamped version](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8-and-supervison.ipynb) of this Notebook, which should work without any problems.

**Comment by SkalskiP** [comment]
I'm closing this issue. Don't hesitate to ask if anything is unclear.

**Comment by chinmayeebidaye** [comment]
@SkalskiP  ThankYou
