### ISSUE TITLE
It’s GroundedSAM free or not?

### ISSUE THREAD

**Issue by Siwakonrome** [roboflow/notebooks#277]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

It’s GroundedSAM free or not? If not How to get Api key to using this service?

import cv2
import supervision as sv
from autodistill_grounded_sam import GroundedSAM
from autodistill.detection import CaptionOntology

class GroundedSAMOperator:

  def __init__(self, caption):
    self.caption = caption
    self.base_model = GroundedSAM(ontology=CaptionOntology(self.caption))
    self.classes = base_model.ontology.classes()

  def __call__(self, image):
    detections = self.base_model.predict(image)
    labels = [f"{self.classes[class_id]} {confidence:0.2f}" for _, _, confidence, class_id, _ in detections]
    print(labels)
    return detections

image = cv2.imread("/content/aluminum.jpg")
caption = { "aluminum workpiece": "aluminum" }
grounded_sam_operator = GroundedSAMOperator(caption)
detections = grounded_sam_operator(image)

mask_annotator = sv.MaskAnnotator()

annotated_frame = mask_annotator.annotate(
        scene=image.copy(),
        detections=detections)

sv.plot_image(annotated_frame, size=(8, 8))

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
I'm not sure if this repository is the best place for this ticket. I recommend moving it to [autodistill](https://github.com/roboflow/autodistill). To answer your question, the `API_KEY` is free; you only need it to download the model from Roboflow.

**Comment by Siwakonrome** [comment]
Yes. I need to use it without internet in my project. If i using autodistill-grounded-sam and download model to my computer work station. That mean i can using this code without API key anymore?

**Comment by SkalskiP** [comment]
@Siwakonrome once the model is cached you don't need internet anymore.

**Comment by Siwakonrome** [comment]
Yes. My project can not connect internet after deployed it on production.

**Comment by SkalskiP** [comment]
I'm closing the issue :)
