### ISSUE TITLE
Minor mistake in yolov8 notebook instruction on yolo version custom dataset download format

### ISSUE THREAD

**Issue by by12380** [roboflow/notebooks#278]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-instance-segmentation-on-custom-dataset.ipynb#scrollTo=6JHICVjZbVKn

### Bug

In this notebook training using yolov8, instruction in the link above (Step 4: Exporting Dataset) says "Click Export and select the YOLO v5 PyTorch dataset format", but I believe should be "YOLO v8", not "YOLO v5 PyTorch".

### Environment

- Google Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Fixed via #310
