### ISSUE TITLE
Wrong validation image viewing path in YOLOv8 object detection training notebook

### ISSUE THREAD

**Issue by ukicomputers** [roboflow/notebooks#293]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

`train-yolov8-object-detection-on-custom-dataset.ipynb`

### Bug

In following section (_in the notebook_):

>## Inference with Custom Model
>...
>**NOTE:** Let's take a look at few results.
>```py
>import glob
>from IPython.display import Image, display
>
>for image_path in glob.glob(f'{HOME}/runs/detect/predict3/*.jpg')[:3]:
>      display(Image(filename=image_path, width=600))
>      print("\n")
>```

In noted Python code, directory set in glob is set to `predict3` (someone got it wrong because they ran train/detection multiple times, and by default, every new train/detection directory in that dir is set by index, so they set to latest "index"). It should be just `predict`, the default index (_see below_).

```py
import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/detect/predict/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")
```

### Environment

- Google Colab

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @ukicomputers 👋🏻 thanks for pointing this out! I noticed that you checked `Yes I'd like to help by submitting a PR!`. Feel free to submit PR with the fix.

**Comment by SkalskiP** [comment]
This issue was solved via https://github.com/roboflow/notebooks/pull/295.
