### ISSUE TITLE
 ModuleNotFoundError: No module named 'sam2'

### ISSUE THREAD

**Issue by eddy961206** [roboflow/notebooks#299]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

grounded-sam-2-auto-label.ipynb

### Bug

I didn't modify 'grounded-sam-2-auto-label.ipynb'.

When I execute 
'from autodistill_grounded_sam_2 import GroundedSAM2' 
cell, 

I get an error like this : 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-3ce49b56a756>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from autodistill_grounded_sam_2 import GroundedSAM2

2 frames
[/usr/local/lib/python3.10/dist-packages/autodistill_grounded_sam_2/helpers.py](https://localhost:8080/#) in load_SAM()
     77         urllib.request.urlretrieve(url, SAM_CHECKPOINT_PATH)
     78 
---> 79     from sam2.build_sam import build_sam2
     80     from sam2.sam2_image_predictor import SAM2ImagePredictor
     81 

ModuleNotFoundError: No module named 'sam2'

I exectued 'pip install git+https://github.com/autodistill/autodistill-grounded-sam-2 rf_groundingdino -q' this cell  before. but I can't find why it can't find module named 'sam2'.

### Environment

- Google Colab
- Window
-

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @capjamesg 👋🏻 could you take a look at this?

**Comment by capjamesg** [comment]
@eddy961206 I have just pushed a fix to the `autodistill-grounded-sam-2` package. This issue should now be fixed. Can you try to run the notebook again? 

Please note that installation may take several minutes as SAM 2 is a large package that takes a while to build in development environments.

**Comment by eddy961206** [comment]
@capjamesg It works perfectly. Thanks for your great work!!!
