### ISSUE TITLE
how to add grouped convolutions and dilated convolutions into the detr-resnet 50 model?

### ISSUE THREAD

**Issue by Gargeya2003** [roboflow/notebooks#313]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

I am doing a project to increase speed and increase the spatil context capturing of the detr model so I want to add grouped convolutions and dilated convolutions to the backbone but I am not able to understand how to modify this from the existing DetrforObjectDetection module from hugging face. Help me out.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @Gargeya2003 👋 

Unfortunately, this is out of scope for roboflow notebooks repository.

Closing the issue.
