### ISSUE TITLE
how to add grouped convolutions and dilated convolutions into the detr-resnet 50 model? #436

### ISSUE THREAD

**Issue by Gargeya2003** [roboflow/notebooks#314]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

I want to use this detr for my project but i want to train this using grouped convolutions and dilated convolutions layers.So how to add them

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @Gargeya2003,

I gave our answer already in your previous question. This is not something we can help with.
