### ISSUE TITLE
ValueError: xyxy must be a 2D np.ndarray with shape (_, 4), but got shape (0, 0, 4)

### ISSUE THREAD

**Issue by FrankTseng168** [roboflow/notebooks#342]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

how_to_finetune_florence_2_on_detection_dataset

### Bug

![image](https://github.com/user-attachments/assets/aecd8e6e-c144-4019-8b0e-5fc7b798d025)

### Environment

win 11/ python3.11.10/ spyder 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @FrankTseng168 👋 

Thank you for the report! I'm failing to reproduce it so far. Do you know when this happens?

Any chance you could print out the shape of `prediction.xyxy`, before `prediction =  prediction[np.isin(...)]`? Also, are there any matches in classes, for `prediction["class_name"]`?

**Comment by FrankTseng168** [comment]
Hi, LinasKo ***@***.***>

Thank you for your email。Please refer to the following result:

 prediction = sv.Detections.from_lmm(sv.LMM.FLORENCE_2, prediction,
resolution_wh=image.size)

    print(prediction.xyxy)
    print(prediction.xyxy.shape)
    print(prediction['class_name'])

    prediction = prediction[np.isin(prediction['class_name'], CLASSES)]
->
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['bed']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['table']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['chair']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['furniture']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['bed']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['tablecloth']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['table']
[[198.72    182.08    227.51999 224.95999]
 [311.36    189.12    409.28    408.63998]]
(2, 4)
['human face' 'person']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['bed']
[[3.2000e-01 3.2000e-01 6.3904e+02 6.3904e+02]]
(1, 4)
['human face']
[]
(0, 4)
None

LinasKo ***@***.***> 於 2024年11月27日 週三 下午10:38寫道：

**Comment by LinasKo** [comment]
The fix is now deployed to our `develop` branch. You can install it with `pip install git+https://github.com/roboflow/supervision.git@develop`.

Thank you for the report, @FrankTseng168!
