### ISSUE TITLE
Dimension Error

### ISSUE THREAD

**Issue by fatihcihant** [roboflow/notebooks#52]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

train-yolov8-object-detection-on-custom-dataset.ipynb
https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb

### Bug

When I run the training cell, I get the error in the image.
![train-yolov8-object-detection-on-custom-dataset ipynb adlı not defterinin kopyası - Colaboratory - Opera 24 01 2023 13_56_03](https://user-images.githubusercontent.com/44322886/214274589-8eadf53a-c75a-4ef2-9c12-f3145adde0fe.png)

### Environment

Google Colab

### Minimal Reproducible Example

%cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 imgsz=416

### Additional

my ipynb link: https://colab.research.google.com/drive/1VyZulDnFdyZmz613v-nVc8gYuNCToz7s?usp=share_link

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @fatihcihant 👋🏻! I'm afraid the source of that issue lies in the YOLOv8 library, not our notebooks. We encountered that issue in the past, and they still could not find the source. I found a few issues already that mention the same exception:
- https://github.com/ultralytics/ultralytics/issues/473
- https://github.com/ultralytics/ultralytics/issues/363
- https://github.com/ultralytics/ultralytics/issues/335

For now, there is only a workaround, not a proper fix. It will train if you add `v5loader=true` to your training command.

```bash
!yolo task=detect \
mode=train \
model=/content/yolov8s.pt \
data=/content/datasets/Human-Dataset-v2-6/data.yaml \
epochs=50 \
imgsz=800 \
v5loader=true
```

**Comment by assia855** [comment]
@SkalskiP thanks for sharing this tip. I face the same error as @fatihcihant  and after adding `v5loader=true` it produces another error. Thanks for your  help.

`    masks = batch["masks"].to(self.device).float()
KeyError: 'masks'`

**Comment by SkalskiP** [comment]
@assia855 / @fatihcihant I'm trying my best. Some problems are just impossible to solve by us. They need to be handled by the YOLOv8 team. I'm determined to help you all as much as I can. 

@assia855 do you train object detection or instance segmentation model? Could you maybe share a link to your copy of the notebook?

**Comment by assia855** [comment]
Thanks for your reply @SkalskiP  I'm working locally  to train instance segmentation model. Can you provide the link to the dataset that you train with it the model I would like to compare. For the label I should use polygon or rectangle please.

**Comment by fatihcihant** [comment]
Yes it works for me too. Thanks for help.
