### ISSUE TITLE
YOLOv5 object detection Colab notebook does not open

### ISSUE THREAD

**Issue by mo-traor3-ai** [roboflow/notebooks#58]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/89935638/216412814-535080d2-83d0-4724-9d66-9ab56d79cf04.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/89935638/216412948-253e5388-9d3e-4f25-bd31-fa8664dd99f5.png">

### Bug

The YOLOv5 Pytorch object detection notebook fails to open

### Environment

Google Chrome / Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Jacobsolawetz** [comment]
@SkalskiP and I just fixed https://github.com/roboflow/notebooks/pull/57
