### ISSUE TITLE
FileNotFoundError: /content/clips/08fd33_4.mp4 does not exist

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [roboflow/notebooks#65]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

how-to-track-football-players.ipynb

### Bug

/content/yolov5
detect: weights=['yolov5x.pt'], source=/content/clips/08fd33_4.mp4, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=coco, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-89-g35d6d9f Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5x.pt to yolov5x.pt...
100% 166M/166M [00:05<00:00, 31.3MB/s]

Fusing layers... 
YOLOv5x summary: 444 layers, 86705005 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 261, in <module>
    main(opt)
  File "detect.py", line 256, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 111, in run
    dataset = LoadImages(source, img_size=imgsz, stride=stride, auto=pt, vid_stride=vid_stride)
  File "/content/yolov5/utils/dataloaders.py", line 254, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /content/clips/08fd33_4.mp4 does not exist

### Environment

the same as yours

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @Ishihara-Masabumi 👋🏻! I just tested the notebook and it works... all fine. Are you sure you downloaded videos from Kaggle?

**Comment by SkalskiP** [comment]
Hi @Ishihara-Masabumi 👋🏻 Any updates?

**Comment by SkalskiP** [comment]
I'm closing the issue :)
