### ISSUE TITLE
Permission error while importing the library

### ISSUE THREAD

**Issue by rudro12356** [roboflow/notebooks#66]
I'm trying to import the roboflow library but am getting:
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[46], line 1
----> 1 from roboflow import Roboflow
      3 # this is from the roboflow public dataset - they have all sort of datasets to work with Yolov5
      4 # so we went with it to make our work easier

File <frozen importlib._bootstrap>:991, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:971, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:914, in _find_spec(name, path, target)

File <frozen importlib._bootstrap_external>:1407, in find_spec(cls, fullname, path, target)

File <frozen importlib._bootstrap_external>:1376, in _get_spec(cls, fullname, path, target)

File <frozen importlib._bootstrap_external>:1340, in _path_importer_cache(cls, path)

PermissionError: [Errno 1] Operation not permitted

I'm using a M2 Pro MACBOOK with pytorch environment managed by anaconda. I found this: 
roboflow                  0.2.29                   pypi_0    pypi

Thanks!

**Comment by SkalskiP** [comment]
Hi, @rudro12356 👋🏻 !

I'm sorry for the late reply, that was a busy week. Is that happening when you try to import `roboflow` pip package?

**Comment by rudro12356** [comment]
> @rudro12356 is this the full stack trace? The part that you pasted is from some library but not directly from roboflow

Hello. Extremely sorry for replying late. Got busy with school. I just tried it now and the dataset was downloadable. Thanks!

**Comment by rudro12356** [comment]
> @rudro12356 is this the full stack trace? The part that you pasted is from some library but not directly from roboflow

Hello. Extremely sorry for replying late. Got busy with school. I just tried it now and the dataset was downloadable. Thanks!

**Comment by SkalskiP** [comment]
Hi, @rudro12356 👋🏻! I'm super happy to hear that.
