### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by zyakubova86** [roboflow/notebooks#77]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

Hi! I tried to train instance segmentation on a custom dataset with roboflow notebook but when I started training part it throw runtime error. please help me to fix this error. I tried the dataset in my local machine also. the same error is showing up. Whats wrong with the dataset?
Dataset 

![image](https://user-images.githubusercontent.com/74640447/222966712-6f4efaae-96e2-4f16-a02c-514d2d9c68dc.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @zyakubova86 👋🏻! Could you share the link to the dataset you used?
