### ISSUE TITLE
 Sizes of tensors must match except in dimension 1. Expected size 57 but got size 0 for tensor number 1 in the list

### ISSUE THREAD

**Issue by Caliphamin** [roboflow/notebooks#84]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[train-yolov8-instance-segmentation-on-custom-dataset](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-instance-segmentation-on-custom-dataset.ipynb)

### Bug

hello
i want to instance segmentation with yolov8 but i've got this error and i am stuck here
i use this command to run yolov8 
!yolo task=segment mode=train model=yolov8m-seg.pt data={dataset.location}/data.yaml epochs=100 imgsz=1024 batch=8
my images width and height are 1024x1024
i get this error

 Sizes of tensors must match except in dimension 1. Expected size 57 but got size 0 for tensor number 1 in the list.
Sentry is attempting to send 1 pending error messages

also when i change image sizes or batch size the number of expected size changed in error 

### Environment

google colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @Caliphamin 👋🏻! Could you share a link to the dataset you used?

**Comment by SkalskiP** [comment]
I'm closing that issue. Feel free to reopen it if needed.
