### ISSUE TITLE
Get error on classification training when using custom dataset in yolo v8

### ISSUE THREAD

**Issue by Sayed049** [roboflow/notebooks#92]
in detection and segmentation 'custom training' i use (data='data.yaml'), see in the image below  ![Screenshot_1](https://user-images.githubusercontent.com/69817491/229864937-525fafb2-8b2f-4b4e-a5c7-8e60cca7afdb.png)

but in classification 'custom training' i use (data='data.yaml') bt get the error, see in the image below  
![Screenshot_2](https://user-images.githubusercontent.com/69817491/229865899-c720d8d6-44ed-41a1-ac68-d0dbe46fb927.png)
i your notebook u tell data=dataset.location bt i dont understand where did i get dataset.location ?

**Comment by SkalskiP** [comment]
Here is the command we use for training in our notebook: `!yolo task=classify mode=train model=yolov8n-cls.pt data={dataset.location} epochs=50 imgsz=128`. For classification, you do not pass `data.yaml`. You pass a directory containing images. 

I am closing the issue. Feel free to reopen in case you'll have more questions.
