### ISSUE TITLE
Get error on classification when using my own dataset in yolo_v8 algo

### ISSUE THREAD

**Issue by Sayed049** [roboflow/notebooks#95]
as i see on your roboflow notebook i make a new directory and put that path into classification training 'data' but it still show error,,i tried even in my drive i also add a new directory then copy that path into classification training 'data' bt unfortunately it still show error,,plz solve this issue, this is the issue screen shot
![Screenshot_1](https://user-images.githubusercontent.com/69817491/230344037-9f98e132-fd4f-48e1-8169-f7497daac9d0.png)

and this is my directory where i keep my data:
![Screenshot_2](https://user-images.githubusercontent.com/69817491/230344533-7be9d8aa-4148-4785-a79a-4d0ee221b702.png)

**plz plz solve this issue**

**Comment by SkalskiP** [comment]
Hi, @Sayed049 👋🏻! I'm sorry for the late response. Does that problem occur in our current notebook version? What is the dataset that you used?

**Comment by SkalskiP** [comment]
Hi, @Sayed049 this issue appears to be no longer active. I'm closing it, but feel free to reopen it in the future.
